name: Clone, Build, and Push Backend Docker Image

on:
  push:
    branches:
      - Maha-Kefi12-patch-1
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout trigger repo (this repo)
      uses: actions/checkout@v4

    - name: Clone backend repository
      run: |
        git clone https://github.com/Maha-Kefi12/WorkingDir1.git Cloud_In_MyPocket

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ 12mahe }}
        password: ${{ dckr_pat_uTmr8IkEFR22wgEjmNsQP5v-Moc }}

    - name: Build and push backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Cloud_In_MyPocket  # Uses the cloned repo as Docker build context
        push: true
        tags: 12mahe/backend:latest
